### ISSUE TITLE
Unable to spawn Code via child_process.exec

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode-extensionbuilders#101]
When I try to spawn another **Code** instance using `child_process.exec`, nothing happens (neither an error). 

```
    exec('start \"open ui\" "C:\\Program Files\\Microsoft VS Code\\Code.exe" "C:\\Program Files\\Winmerge\\Files.txt"').
```

Original from issue #84

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#570
