### ISSUE TITLE
Extension Gallery styles

### ISSUE THREAD

**Issue by mikiest** [Microsoft/vscode-extensionbuilders#108]
The **readme.md** displayed in the Extension Gallery doesn't respect all the styles I think it should.

For instance:

- H<1,2..> all have the same font size
- Multi line code quotes look like plain text
- Inline code quotes look like plain text

I hope this helps the Extension Gallery look great for the public release :)
Other than that, it is awesome!

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#568

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#572
