### ISSUE TITLE
Extension is not deactivated on closing the editor window

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode-extensionbuilders#113]
My extension spins up a few processes that I'd like to kill when it's deactivated.
The deactivation callback for `ExtensionContext`
``` JavaScript
context.subscriptions.push({dispose: () => ...});
```
works perfectly when I stop debugger for the Extension Development Host. However, if I just close the editor window on OSX, the deactivation callback is not invoked, so I can see all created processes hanging around and not being killed.

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#567
