### ISSUE TITLE
Allow to open non-text files via API

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode-extensionbuilders#117]
I can open an image (PNG) in the editor manually and there's `workspace.openTextDocument`, but, as expected from the function name, I can't use it to open the image file: `"cannot open file:///.... Detail: File seems to be binary and cannot be opened as text"`. Perhaps there should be another function, such as `openFile` that could open any supported file type?

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#566
