### ISSUE TITLE
Provide an API for advanced source highlighting

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode-extensionbuilders#14]
I'm looking for a way to implement an advanced source highlighting 
where a language service changes the color of words in a file. The result would look similar to the output Visual Studio creates in C# files. 
The screenshot shows C# code in Visual Studio. The word "Customer" is highlighted differently based on its context:
![advancedhighlighting](https://cloud.githubusercontent.com/assets/3448684/10456067/6b53769e-71bf-11e5-95b3-f2e95348101b.PNG)

To implement highlighting like this it's necassary to let a language service decide about the color of a word after the grammar based highlighter has done its job.
I would like to see an API for this in the future.

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#585
