### ISSUE TITLE
Link to a file position in Output Channel

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode-extensionbuilders#41]
As mentioned in [this issue](https://github.com/Microsoft/vscode-extensionbuilders/issues/19#issuecomment-148695187), output channel supports link rendering. I'd like to append a link to a workspace file position (by providing a file name, line and column in some form). If it's already possible, could you please paste an example on how to do it?

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#586
