### ISSUE TITLE
How to read languages/colorizer settings?

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode-extensionbuilders#57]
How could I get  some language/colorizer settings?

I'm creating an extension to add personalized comments, and would like to get the _line comment_ language/colorizer setting (`//`, `#`, etc) from the current language.

I did take a look at [vscode-comment](https://github.com/Microsoft/vscode-comment) demo and `export interface ILanguage`, but didn't find how to _read_ the setting.

Thanks in advance

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#591
