### ISSUE TITLE
Add Quick info panel 

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode-extensionbuilders#6]
Quick Info panel is "small margin located at the bottom of the code editor. It automatically shows errors and warnings under the cursor, eliminating the need to use mouses to see tooltips with the same info." 

That's how it looks like in Ionide Atom - 
![image](https://cloud.githubusercontent.com/assets/5427083/10418149/4e564d68-7053-11e5-96ce-ef123dfd91da.png) Same feature is also implemented in Visual F# Power Tools - https://fsprojects.github.io/VisualFSharpPowerTools/quickinfopanel.html

IMO, it might be interesting addition to language services API.

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#584
