### ISSUE TITLE
Add onDidStopChangingTextDocument

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode-extensionbuilders#61]
Idea is to add new event on workspace which will fire whenever user stop editing document for X milliseconds.

The problem with `onDidChangeTextDocument` is that it fires on every key stroke what is often not necessary (or not possible for more expensive / longer operations).

Implementing it is easy (just a timeout (re)started on every `onDidChangeTextDocument` ) but I think it would be nice to have built-in helper for it in API.

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#590
