### ISSUE TITLE
Support Extensions Providing TypeScript Definition Files

### ISSUE THREAD

**Issue by thoughtentity** [Microsoft/vscode-extensionbuilders#64]
As part of the extension I'm developing, I'm developing a TypeScript definition file to light up the editor with intellisense for the JavaScript APIs my users will be using when working with my extension in their project. Currently, to support this I need to explicitly inject the type definition files into a user's project through an init command provided by the extension. I'd be nice if VS Code supported this scenario better by implicitly loading definition files from an extension's typings directory. Users can override the extension provided definitions by providing their own type definition files that redefine the typings the extension provided.

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#589
