### ISSUE TITLE
Support autoClosingPairs for strings like `begin` and `end`

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode-extensionbuilders#66]
I'd like to define `autoClosingPairs` for Pascal like `begin <-> end`, `if <-> then` etc.
Definitions for closing pairs like these seem to be ignored by VSCode. It looks like auto closing is currently supported for character pairs only. 

Please add support for longer auto closing pairs.

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#583
