### ISSUE TITLE
Can I get scope / scopeRange at a position?

### ISSUE THREAD

**Issue by billti** [Microsoft/vscode-extensionbuilders#76]
The API call `document.getWordRangeAtPosition(position)` appears to use its own definition of a word. For example, my tmLanguage defines `attrib-name` as a token/scope, yet `getWordRangeAtPosition` appears to break this into 2 words on the `-` character.

How can I get token ranges at a position based on my custom syntax? (And it would be really useful if I could get the scope name that goes along with it too).

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#580
