### ISSUE TITLE
contributing key bindings by including files

### ISSUE THREAD

**Issue by guillermooo** [Microsoft/vscode-extensionbuilders#82]
From the docs, it seems that extensions need to include the key bindings in the manifest proper. For extensions that will contribute a lot of key bindings, it may be more convenient to include *files* of key binding definitions.

Example:

```json
...
"contributes": {
    "keybindings": [{
        "command": "extension.sayHello",
        "key": "ctrl+f1",
        "mac": "cmd+f1",
        "when": "editorTextFocus"
    },
    { "include": "motions.json" },
    { "include": "actions.json" }
  ]
}
...
```

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#579
