### ISSUE TITLE
keybindings should not work in normal mode by default

### ISSUE THREAD

**Issue by guillermooo** [Microsoft/vscode-extensionbuilders#83]
For Vim emulation, there needs to be a way to capture key strokes and suppress them before they are inserted in the buffer. That is, normal mode in Vim.

In other editors, it's a problem that all key bindings work by default in normal mode. Because plugins are loaded alphabetically, there is then a chance that the plugin to load last may override Vim key bindings, even though that plugin isn't interested in normal mode at all and/or doesn't even work when the editor is in normal mode.

When VS Code enables a variant of normal mode (when? :-)), I think it'd be best if key bindings had to opt-in explicitly to normal mode.

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#575
