### ISSUE TITLE
A parameterized action to open a file or folder

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode-extensionbuilders#84]
Where can I find documentation for _core commands_, like `workbench.action.files.openFolder`?

I'm creating an extension to switch between projects (folders) and was thinking to use this command, indicating the destination folder (`vscode.commands.executeCommand("workbench.action.files.openFolder", "c:\somefolder\somesubfolder")`). But instead of switching to that folder, it only shows an _open dialog_. 

Of course, I don't know if I'm using the wrong command, or using it wrongly :)

Thanks in advance

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#574
