### ISSUE TITLE
How to get whole CompletionItems that vscode provided in language service API "registerCompletionItemProvider"?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode-extensionbuilders#89]
I want to develop an extension for JavaScript Intellisense in VSCode , And now i meet an problem that when i call the API "registerCompletionItemProvider" in the following code , i can't get the whole completionItems that provided by the VSCode itself in method "provideCompletionItems",anyone can help me?

      vscode.languages.registerCompletionItemProvider("javascript",
	{
		resolveCompletionItem(item:vscode.CompletionItem, token: vscode.CancellationToken): vscode.CompletionItem 
		{
			
		   var completionItem1:vscode.CompletionItem = new vscode.CompletionItem("id");
		   completionItem1.detail = "aaa";
		   completionItem1.filterText = "aa";
		   completionItem1.insertText = "aa";
		   return completionItem1;
		}
		,
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): Promise<vscode.CompletionItem[]> 
		{
        // I want to get 	completionItems that provided by the VSCode itself ,not like following code ,provided by myself. does any variable has stored completionItems.

			return new Promise((resolve, reject) => { 
			var completionItems:vscode.CompletionItem[] = [];
			var completionItem:vscode.CompletionItem = new vscode.CompletionItem("bb");
			completionItem.detail = "bde";
			completionItem.filterText = "bb";
			completionItem.insertText = "bb";
			completionItems.push(completionItem);
			return resolve(completionItems) ;
						});
		}
	})

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#578
