### ISSUE TITLE
rewrite completion list ui

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode-extensionbuilders#99]
As we know , when you write JavaScript code in VSCode ,it will popup an Completion list UI as following.
![vscode](https://cloud.githubusercontent.com/assets/15098626/11115402/46d811bc-8966-11e5-919e-5b21bf3fe0e7.png)
I want to know whether i can overwrite the Completion list UI ,because i want to provide additional information for each JavaScript API, anyone can help me ?

**Comment by seanmcbreen** [comment]
This issue was moved to Microsoft/vscode#573
